<a href="https://colab.research.google.com/github/Voltaire01-W/DS-Unit-2-Linear-Models/blob/master/Copy_of_LS_DS_214_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lambda School Data Science

*Unit 2, Sprint 1, Module 4*

---

# Logistic Regression


## Assignment 🌯

You'll use a [**dataset of 400+ burrito reviews**](https://srcole.github.io/100burritos/). How accurately can you predict whether a burrito is rated 'Great'?

> We have developed a 10-dimensional system for rating the burritos in San Diego. ... Generate models for what makes a burrito great and investigate correlations in its dimensions.

- [ ] Do train/validate/test split. Train on reviews from 2016 & earlier. Validate on 2017. Test on 2018 & later.
- [ ] Begin with baselines for classification.
- [ ] Use scikit-learn for logistic regression.
- [ ] Get your model's validation accuracy. (Multiple times if you try multiple iterations.)
- [ ] Get your model's test accuracy. (One time, at the end.)
- [ ] Commit your notebook to your fork of the GitHub repo.


## Stretch Goals

- [ ] Add your own stretch goal(s) !
- [ ] Make exploratory visualizations.
- [ ] Do one-hot encoding.
- [ ] Do [feature scaling](https://scikit-learn.org/stable/modules/preprocessing.html).
- [ ] Get and plot your coefficients.
- [ ] Try [scikit-learn pipelines](https://scikit-learn.org/stable/modules/compose.html).

In [0]:
%%capture
import sys

# If you're on Colab:
if 'google.colab' in sys.modules:
    DATA_PATH = 'https://raw.githubusercontent.com/LambdaSchool/DS-Unit-2-Linear-Models/master/data/'
    !pip install category_encoders==2.*

# If you're working locally:
else:
    DATA_PATH = '../data/'

In [0]:
# Load data downloaded from https://srcole.github.io/100burritos/
import pandas as pd
df = pd.read_csv(DATA_PATH+'burritos/burritos.csv')

In [0]:
# Derive binary classification target:
# We define a 'Great' burrito as having an
# overall rating of 4 or higher, on a 5 point scale.
# Drop unrated burritos.
df = df.dropna(subset=['overall'])
df['Great'] = df['overall'] >= 4

In [0]:
# Clean/combine the Burrito categories
df['Burrito'] = df['Burrito'].str.lower()

california = df['Burrito'].str.contains('california')
asada = df['Burrito'].str.contains('asada')
surf = df['Burrito'].str.contains('surf')
carnitas = df['Burrito'].str.contains('carnitas')

df.loc[california, 'Burrito'] = 'California'
df.loc[asada, 'Burrito'] = 'Asada'
df.loc[surf, 'Burrito'] = 'Surf & Turf'
df.loc[carnitas, 'Burrito'] = 'Carnitas'
df.loc[~california & ~asada & ~surf & ~carnitas, 'Burrito'] = 'Other'

In [0]:
# Drop some high cardinality categoricals
df = df.drop(columns=['Notes', 'Location', 'Reviewer', 'Address', 'URL', 'Neighborhood'])

In [0]:
# Drop some columns to prevent "leakage"
df = df.drop(columns=['Rec', 'overall'])

In [95]:
df.head()

Burrito       Date  Yelp  Google Chips  ...  Sushi  Avocado  Corn  Zucchini  Great
0  California  1/18/2016   3.5     4.2   NaN  ...    NaN      NaN   NaN       NaN  False
1  California  1/24/2016   3.5     3.3   NaN  ...    NaN      NaN   NaN       NaN  False
2    Carnitas  1/24/2016   NaN     NaN   NaN  ...    NaN      NaN   NaN       NaN  False
3       Asada  1/24/2016   NaN     NaN   NaN  ...    NaN      NaN   NaN       NaN  False
4  California  1/27/2016   4.0     3.8     x  ...    NaN      NaN   NaN       NaN   True

[5 rows x 59 columns]

In [96]:
df['Date'] = pd.to_datetime(df['Date'])
df = df.set_index(df['Date'])
df = df.sort_index()
df

Burrito       Date  Yelp  Google  ... Avocado  Corn  Zucchini  Great
Date                                             ...                               
2011-05-16       Other 2011-05-16   NaN     NaN  ...     NaN   NaN       NaN  False
2015-04-20       Other 2015-04-20   NaN     NaN  ...     NaN   NaN       NaN   True
2016-01-18  California 2016-01-18   3.5     4.2  ...     NaN   NaN       NaN  False
2016-01-24       Asada 2016-01-24   NaN     NaN  ...     NaN   NaN       NaN  False
2016-01-24  California 2016-01-24   3.5     3.3  ...     NaN   NaN       NaN  False
...                ...        ...   ...     ...  ...     ...   ...       ...    ...
2019-08-27       Asada 2019-08-27   NaN     NaN  ...     NaN   NaN       NaN   True
2019-08-27       Other 2019-08-27   NaN     NaN  ...     NaN   NaN       NaN   True
2019-08-27       Other 2019-08-27   NaN     NaN  ...     NaN   NaN       NaN   True
2019-08-27       Other 2019-08-27   NaN     NaN  ...     NaN   NaN       NaN   True
2026-04-25  California 2026-04-25   NaN     NaN  ...     NaN   NaN       NaN   True

[421 rows x 59 columns]

In [97]:
df.isnull().sum()

Burrito             0
Date                0
Yelp              334
Google            334
Chips             395
Cost                7
Hunger              3
Mass (g)          399
Density (g/mL)    399
Length            138
Circum            140
Volume            140
Tortilla            0
Temp               20
Meat               14
Fillings            3
Meat:filling        9
Uniformity          2
Salsa              25
Synergy             2
Wrap                3
Unreliable        388
NonSD             414
Beef              242
Pico              263
Guac              267
Cheese            262
Fries             294
Sour cream        329
Pork              370
Chicken           400
Shrimp            400
Fish              415
Rice              385
Beans             386
Lettuce           410
Tomato            414
Bell peper        414
Carrots           420
Cabbage           413
Sauce             383
Salsa.1           414
Cilantro          406
Onion             404
Taquito           417
Pineapple 

In [98]:
train = df[df['Date'].dt.year < 2017]
val = df[df['Date'].dt.year == 2017]
test = df[df['Date'].dt.year > 2017]
print(train)
print(val)
print(test)

               Burrito       Date  Yelp  Google  ... Avocado  Corn  Zucchini  Great
Date                                             ...                               
2011-05-16       Other 2011-05-16   NaN     NaN  ...     NaN   NaN       NaN  False
2015-04-20       Other 2015-04-20   NaN     NaN  ...     NaN   NaN       NaN   True
2016-01-18  California 2016-01-18   3.5     4.2  ...     NaN   NaN       NaN  False
2016-01-24       Asada 2016-01-24   NaN     NaN  ...     NaN   NaN       NaN  False
2016-01-24  California 2016-01-24   3.5     3.3  ...     NaN   NaN       NaN  False
...                ...        ...   ...     ...  ...     ...   ...       ...    ...
2016-12-02  California 2016-12-02   4.0     4.3  ...     NaN   NaN       NaN  False
2016-12-02       Other 2016-12-02   NaN     NaN  ...     NaN   NaN       NaN  False
2016-12-10  California 2016-12-10   3.5     3.7  ...     NaN   NaN       NaN  False
2016-12-10       Asada 2016-12-10   NaN     NaN  ...     NaN   NaN       NaN

In [0]:
#from sklearn.model_selection import train_test_split

#train, val = train_test_split(train, random_state=42)
#train.shape, val.shape, test.shape

In [0]:
df = df.replace({False:0, True:1})

In [101]:
train['Great'].value_counts()

False    176
True     122
Name: Great, dtype: int64

In [102]:
target = 'Great'
y_train = train[target]
y_train.value_counts(normalize=True)

False    0.590604
True     0.409396
Name: Great, dtype: float64

In [103]:
majority_class = y_train.mode()[0]
y_pred = [majority_class] * len(y_train)
y_pred

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,


In [104]:
from sklearn.metrics import accuracy_score

accuracy_score(y_train, y_pred)

0.5906040268456376

In [105]:
y_val = val[target]
y_pred = [majority_class] * len(y_val)
accuracy_score(y_val, y_pred)

0.5529411764705883

In [106]:
from sklearn.linear_model import LinearRegression

linear_reg = LinearRegression()

features = ['Uniformity', 'Tortilla', 'Synergy']
X_train = train[features]
X_val = val[features]

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
X_train_imputed = imputer.fit_transform(X_train)
X_val_imputed = imputer.transform(X_val)

linear_reg.fit(X_train_imputed, y_train)

linear_reg.predict(X_val_imputed)

array([ 0.51829848,  0.57470707,  0.58156982,  0.5352581 , -0.15648805,
        0.53777128,  0.74817574, -0.42765066,  0.22440479,  0.74691395,
        0.76835736, -0.35313072,  0.13703309,  1.01591514,  0.33367576,
        0.41679245,  0.53777128,  0.54338349,  0.52286559,  1.01591514,
        0.40477249,  0.59396232,  0.22797517,  0.56529485,  0.64384443,
        0.56529485,  0.52286559,  0.43343997,  0.76056824,  0.87866134,
        0.76056824,  0.44720175,  0.29124651,  0.4546546 ,  0.29331252,
        0.34146488,  0.65129727,  0.34057564,  0.6226298 ,  0.27922655,
        0.26546477,  0.48788918,  0.42918495,  0.4546546 ,  0.67996474,
        0.63008264, -0.01923425, -0.14903521,  0.29975654,  0.44720175,
        0.40477249,  0.18691519,  0.77889713,  0.66962616,  0.50165096,
        0.11972511,  0.46416136,  0.24425014,  0.28873332, -0.30613436,
        0.42598712, -0.06417669,  0.45441372,  0.4546546 ,  0.41222534,
        0.89493631,  0.49708385,  0.66505905,  0.60598228,  0.34

In [107]:
pd.Series(linear_reg.coef_, features)

Uniformity    0.042429
Tortilla      0.099764
Synergy       0.293521
dtype: float64

In [108]:
test_case = [[3, 3, 3]]
linear_reg.predict(test_case)

array([0.18691519])

In [109]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(solver='lbfgs')
log_reg.fit(X_train_imputed, y_train)
print('Validation Accuracy', log_reg.score(X_val_imputed, y_val))

Validation Accuracy 0.7764705882352941


In [110]:
log_reg.predict(X_val_imputed)

array([ True,  True,  True,  True, False,  True,  True, False, False,
        True,  True, False, False,  True, False, False,  True,  True,
        True,  True, False,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True, False, False, False, False, False,
        True, False,  True, False, False, False, False, False,  True,
        True, False, False, False, False, False, False,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False,  True,  True, False,  True,  True,
        True,  True, False, False,  True, False,  True,  True, False,
       False, False,  True,  True])

In [111]:
log_reg.predict(test_case)

array([False])

In [112]:
pd.Series(log_reg.coef_[0], features)

Uniformity    0.395834
Tortilla      0.753924
Synergy       2.427589
dtype: float64

In [113]:
pd.Series(linear_reg.coef_, features)

Uniformity    0.042429
Tortilla      0.099764
Synergy       0.293521
dtype: float64

In [114]:
log_reg.intercept_

array([-13.45987835])

In [0]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.e**(-x))

In [116]:
sigmoid(log_reg.intercept_ + np.dot(log_reg.coef_, np.transpose(test_case)))

array([[0.06135048]])

In [122]:
y_test = test[target]
X_test = test[features]
X_test_imputed = imputer.fit_transform(X_test)
log_reg.fit(X_test_imputed, y_test)
print('Test Accuracy', log_reg.score(X_test_imputed, y_test))

Test Accuracy 0.8421052631578947
